[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x", "openssl"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm install && npm run build"]

[start]
cmd = "npm run deploy && npm run start:prod"

